# app/config/application.yml
defaults: &defaults
  salt_token: 'Cn+7#mQM-~]9=hK%cLZ.F\[2_YEH=sjcFVO}Ws6TL3uWJ1C.&5Zs3F)GNivsJ;?W'
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
